export type PostSlugRedirect = {
  locale: "en" | "es";
  from: string;
  to: string;
};

/**
 * Public replacements for legacy slugs that were generated by stripping
 * accented characters and truncating titles in the middle of a word.
 *
 * Keep these aliases indefinitely so existing links retain their value.
 */
export const POST_SLUG_REDIRECTS: readonly PostSlugRedirect[] = [
  {
    locale: "es",
    from: "extra-ando-lo-que-nunca-fue",
    to: "extranando-lo-que-nunca-fue",
  },
  {
    locale: "es",
    from: "el-dios-que-no-juega-seg-n-nuestras-reglas",
    to: "el-dios-que-no-juega-segun-nuestras-reglas",
  },
  {
    locale: "en",
    from: "the-god-who-doesn-t-play-by-our-rules",
    to: "the-god-who-doesnt-play-by-our-rules",
  },
  {
    locale: "en",
    from: "don-t-take-advice-from-someone-whose-life-you-don-",
    to: "dont-take-advice-from-someone-whose-life-you-dont-want",
  },
  {
    locale: "es",
    from: "no-todo-consejo-viene-envuelto-en-la-vida-que-t-su",
    to: "no-todo-consejo-viene-envuelto-en-la-vida-que-tu-suenas",
  },
  {
    locale: "es",
    from: "qu-significa-realmente-pertenecer",
    to: "que-significa-realmente-pertenecer",
  },
  {
    locale: "en",
    from: "deconstruction-and-beyond-a-story-of-loss-and-rebi",
    to: "deconstruction-and-beyond-a-story-of-loss-and-rebirth",
  },
  {
    locale: "es",
    from: "deconstrucci-n-y-m-s-all-una-historia-de-p-rdida-y",
    to: "deconstruccion-y-mas-alla-una-historia-de-perdida-y-renacimiento",
  },
] as const;

const publicSlugByStoredSlug = new Map(
  POST_SLUG_REDIRECTS.map(({ from, to }) => [from, to]),
);
const storedSlugByPublicSlug = new Map(
  POST_SLUG_REDIRECTS.map(({ from, to }) => [to, from]),
);

export function publicPostSlug(storedSlug: string): string {
  return publicSlugByStoredSlug.get(storedSlug) ?? storedSlug;
}

/** Supports both the current stored slug and a future database cleanup. */
export function postSlugCandidates(publicOrStoredSlug: string): string[] {
  const storedSlug =
    storedSlugByPublicSlug.get(publicOrStoredSlug) ?? publicOrStoredSlug;
  return storedSlug === publicOrStoredSlug
    ? [publicOrStoredSlug]
    : [publicOrStoredSlug, storedSlug];
}

/** Generate readable, ASCII-only slugs without cutting the final word. */
export function slugifyPostTitle(title: string, maxLength = 72): string {
  const slug = title
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[‘’']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

  if (slug.length <= maxLength) return slug;

  const truncated = slug.slice(0, maxLength + 1);
  const lastSeparator = truncated.lastIndexOf("-");
  return (lastSeparator > 0 ? truncated.slice(0, lastSeparator) : truncated)
    .replace(/-+$/g, "");
}
