export const SPANISH_POST_CONTENT_B = {
  "how-to-rebuild-faith-after-deconstruction": [
    "<h2>La vida después de la deconstrucción: ¿hacia dónde vamos?</h2>",
    "<p>Últimamente pienso mucho en cómo es la vida después de deconstruir la fe.</p>",
    "<p>¿Qué quiero decir cuando hablo de deconstrucción?</p>",
    "<p>Para mí, es un proceso de desaprender y volver a aprender. Es cuestionar las creencias con las que creciste y todo aquello que te enseñaron como una verdad incuestionable. De pronto, sistemas que durante años parecían firmes empiezan a resquebrajarse.</p>",
    "<p>No se trata solo de poner esas creencias en duda. Se trata de abrirte a la posibilidad de que quizá no sean ciertas, o de que no lo sean de la manera en que siempre las entendiste.</p>",
    "<h2>Mi vida antes de deconstruir la fe</h2>",
    "<p>Antes de comenzar este proceso, yo era una cristiana profundamente devota. Y cuando digo devota, hablo en serio.</p>",
    "<p>No era solo una joven comprometida con su iglesia. Era misionera a tiempo completo.</p>",
    "<p>Todos mis días giraban alrededor de la misión. No podía salir de casa sin sentir ese peso: tenía que hablarle a alguien del evangelio, de Jesús, del reino de Dios.</p>",
    "<p>En una gasolinera, en un restaurante, en el supermercado. Vivir mi vida cotidiana no era suficiente. Sentía que tenía que proclamar el mensaje. Siempre.</p>",
    "<p>Estudié en un seminario. Formé parte de una iglesia que se reunía en una casa. Vivía y respiraba el cristianismo tal como lo entendía entonces.</p>",
    "<p>El propósito de mi vida era dar a conocer a Jesús: extender el reino, ganar almas, entregar mi vida a la causa.</p>",
    "<p>Y lo hice. Incluso viví un año en el extranjero, entre lo que entonces llamábamos «un pueblo no alcanzado por el evangelio». Aprendí el idioma, me sumergí en la cultura e hice el trabajo.</p>",
    "<p>Ese año me cambió la vida. De maneras hermosas, por los encuentros con personas que nunca olvidaré. Y también de maneras dolorosas, porque fue allí donde se sembraron las primeras semillas de mi deconstrucción.</p>",
    "<h2>Cuando todo empezó a resquebrajarse</h2>",
    "<p>Al vivir desde dentro el mundo de las misiones, también conocí su otra cara.</p>",
    "<p>La superioridad. La dominación. El control sutil y el que no lo era tanto. La imposición de una supuesta verdad a costa de la humanidad de las personas.</p>",
    "<p>Y, una vez que lo vi, ya no pude dejar de verlo.</p>",
    "<p>Cuando regresé, empecé a hacerme preguntas. No ocurrió de un día para otro. Fueron años.</p>",
    "<p>Años desenredando ideas, tirando de los hilos y tomando distancia. Me alejé de la iglesia. Dejé de leer la Biblia como una obligación religiosa, aunque ya la había leído de principio a fin más de cinco veces.</p>",
    "<p>Entendí que la Palabra vive en mí: en mi corazón, en mi cuerpo, en mi sistema nervioso.</p>",
    "<p>¿Y la iglesia? No está atada a un edificio. Ni siquiera está atada a una religión. La iglesia es el amor puesto en práctica.</p>",
    "<h2>Lo que me costó la deconstrucción</h2>",
    "<p>Cuando empecé a cuestionar aquello que antes me definía, todo cambió. Cambiaron mis amistades, mi entorno y la forma en que me entendía a mí misma.</p>",
    "<p>Esta es una realidad difícil: solemos aceptar con más facilidad a quienes se nos parecen, piensan y actúan como lo hacemos, y creen lo mismo. Nos cuesta aceptar la complejidad con compasión y atravesar las contradicciones con gracia.</p>",
    "<p>Por eso, cuando dejas de encajar, a veces te hacen a un lado, de manera consciente o no. Otras veces eres tú quien se aísla.</p>",
    "<p>No se trata de buscar culpables. Es una realidad que he tenido que reconocer.</p>",
    "<h2>La pregunta inevitable: ¿y ahora qué?</h2>",
    "<p>¿A qué viene todo esto?</p>",
    "<p>A que estoy aquí, en medio de esa pregunta: ¿y ahora qué?</p>",
    "<p>¿Qué haces cuando entregaste toda tu vida a algo y luego comprendes que ya no puedes seguir entregándote de la misma manera?</p>",
    "<p>¿Qué haces cuando tu propósito entero era extender el reino de Dios y ahora tienes un trabajo de horario fijo, pagas facturas e intentas cuidar de ti, pero nada de eso parece suficiente?</p>",
    "<p>Durante años me repetí: niégate a ti misma, niega los deseos de tu cuerpo, preocúpate solo por el reino. Pero la verdad es que sí me importan otras cosas.</p>",
    "<p>Me importa dónde vivo. Me importa mi calidad de vida. Me importa mi salud. Me importa la prosperidad. Me importa alcanzar mis metas.</p>",
    "<p>¿Es Dios tan narcisista como para odiar que esas cosas me importen? ¿De verdad quiere que solo me importe Él?</p>",
    "<p>La respuesta es no.</p>",
    "<h2>Aprender una forma nueva de vivir</h2>",
    "<p>Me tomó años comprenderlo.</p>",
    "<p>Para amar a quienes me rodean, tengo que amarme. Para cuidar a otras personas, tengo que cuidarme. Para ofrecer empatía y compasión, primero tengo que tratarme con esa misma empatía y compasión.</p>",
    "<p>Todo está conectado. No son cosas separadas.</p>",
    "<h2>Sigo buscando</h2>",
    "<p>Y, aun así, sigo aquí, preguntándome hacia dónde voy ahora.</p>",
    "<p>¿Hacia dónde vamos quienes, en la infancia, la adolescencia o la adultez, entregamos toda nuestra maldita vida al evangelio?</p>",
    "<p>¿Cómo vivimos a partir de ahora? ¿Cómo encontramos propósito? ¿Cómo seguimos sintiendo que nuestra vida importa más allá de nuestra propia historia?</p>",
    "<p>Porque eso me importa. Me importa que mi vida aporte algo a otras personas.</p>",
    "<h2>La pregunta que no logro soltar</h2>",
    "<p>Este es el lugar en el que estoy hoy: ¿cómo puedo vivir con equilibrio?</p>",
    "<p>No quiero construir el reino de Dios a costa de no construir nada para mí. Tampoco quiero construir mi propio reino a costa de ignorar a Dios.</p>",
    "<p>Quiero ambas cosas. Una vida con propósito y prosperidad. Una vida sagrada y, al mismo tiempo, sostenible.</p>",
    "<p>¿Cómo se hace?</p>",
    "<p>No tengo la respuesta. Tal vez esto sea un grito de ayuda. Tal vez solo necesitaba desahogarme.</p>",
    "<p>Pero quizá las respuestas empiecen a aparecer porque, por fin, me atreví a formular la pregunta.</p>",
    "<p>¿Hacia dónde voy ahora?</p>",
  ].join(""),
  "grief-after-miscarriage-and-the-life-you-imagined": [
    "<p>Creo que está bien extrañar algo y, al mismo tiempo, no querer recuperarlo.</p>",
    "<p>En mi relación anterior, mi pareja y yo esperábamos un bebé, pero sufrimos una pérdida gestacional. Han pasado años y descubro que aún estoy procesando lo que ocurrió.</p>",
    "<h2>El duelo por la vida que imaginé</h2>",
    "<p>Hay días en los que vuelvo a imaginar cómo habría sido mi bebé. Su rostro. Su cabello. Sus ojos, parecidos a los de su padre.</p>",
    "<p>Lo imaginaba de pequeño. Imaginaba el vínculo que tendríamos. Me veía haciendo todo lo posible por darle la vida que yo no tuve, o quizá la vida que me habría gustado tener.</p>",
    "<p>Hoy ya no estoy en aquella relación. Aquel bebé no llegó a nacer. Ahora comparto mi vida con otra persona y soy muy feliz.</p>",
    "<h2>Dos verdades pueden convivir</h2>",
    "<p>Y, aun así, ambas realidades conviven en mí.</p>",
    "<p>Todavía imagino cómo habría sido mi vida si mi bebé hubiera nacido, el rumbo que habría tomado.</p>",
    "<p>No puedo decir que sepa por qué suceden las cosas. Tengo ideas y teorías. La mayoría probablemente sean formas de sobrellevar lo ocurrido. Quizá alguna sea una revelación divina. ¿Qué sé yo?</p>",
    "<p>Pero en días como hoy, siento que mi cuerpo recuerda. Es como si algo hubiese estado destinado a suceder y, sencillamente, no hubiera sucedido.</p>",
    "<p>Y uso la palabra «destinado» según mi propia manera de entender la vida. Porque, si de verdad tenía que suceder, él estaría aquí, ¿no?</p>",
    "<p>Esta es una de las partes más desconcertantes de la experiencia humana: queremos que todo sea blanco o negro, pero no siempre funciona así. A veces hay un poco de todo. Otras veces queda un vacío enorme.</p>",
    "<p>Hoy no extraño lo que tuve. Extraño lo que imaginé que podría llegar a tener.</p>",
    "<p>Todavía me pregunto cómo habría sido esa vida. ¿Debería sentirme culpable? ¿Está mal? ¿Es egoísta sentirlo?</p>",
    "<p>No lo sé.</p>",
    "<h2>Darle permiso al duelo</h2>",
    "<p>Lo que sí sé es esto: está bien vivir un duelo incluso por algo que nunca llegó a suceder. Puedes llorar la vida que imaginaste y la historia que creíste que ibas a vivir.</p>",
    "<p>Porque, lo admita o no, mi cuerpo conoce el duelo. En cuanto hago silencio y me encuentro conmigo misma, aparecen las lágrimas. Es como si mi cuerpo hubiera esperado todo este tiempo a que yo pudiera sentirlas.</p>",
    "<p>Así que sí, esto es lo que hay. Este es el lugar en el que estoy hoy.</p>",
  ].join(""),
  "finding-spiritual-balance-between-faith-and-material-life": [
    "<p>Últimamente he estado pensando en cuánto ha cambiado mi realidad.</p>",
    "<p>Hace una década, yo era profundamente religiosa. En esos espacios suelen enseñarte que debes negarte a ti misma. Esa frase puede significar muchas cosas, pero, dentro del cristianismo evangélico occidental, a menudo termina significando que debes renunciar a tus deseos, a tus sueños y a tu cuerpo. En otras palabras: abandonarte para servir a la misión de Dios, al reino de Dios y a lo que Él tiene para ti.</p>",
    "<p>Y eso fue exactamente lo que hice.</p>",
    "<p>Si tuviera que expresarlo en porcentajes, diría que mi vida espiritual ocupaba entonces el 95 % de mi vida: mis pensamientos, mis oraciones, mis prioridades y mi tiempo. Mi identidad giraba casi por completo alrededor de Dios, la iglesia y el ministerio.</p>",
    "<p>Mi vida material casi no tenía lugar.</p>",
    "<p>No solo no le prestaba atención; estaba convencida de que hacerlo estaba mal. Vivía muy por debajo del umbral de la pobreza, en gran medida porque creía que preocuparse por lo material era poco espiritual. No siempre me lo dijeron de forma explícita, aunque a veces sí, pero el mensaje estaba presente en todas partes: lo material no importaba. Claro que, cuando llegaba el momento de dar el diezmo, sí importaba. Pero esa es otra conversación.</p>",
    "<h2>Cuando sanar se parece a un péndulo</h2>",
    "<p>Últimamente he notado que sanar se parece muchas veces al movimiento de un péndulo. En nuestra búsqueda de una vida más plena, solemos pasar con fuerza de un extremo al otro antes de encontrar el equilibrio.</p>",
    "<p>Y creo que eso es precisamente lo que me está ocurriendo.</p>",
    "<h2>Cuando la seguridad material ocupa casi todo</h2>",
    "<p>Hoy estoy en el extremo opuesto. Diría que ahora destino el 95 % de mi energía a construir seguridad material: encontrar estabilidad, generar ingresos y levantar algo sostenible y próspero.</p>",
    "<p>No quiero juzgar ese deseo. Hay algo profundamente reparador en el simple hecho de poder desearlo, en recuperar aspectos de mí que antes consideraba pecaminosos.</p>",
    "<p>Pero he empezado a reconocer un patrón en mi forma de pensar.</p>",
    "<p>Si logro construir esta vida. Si consigo la casa. Si genero ingresos pasivos. Si alcanzo ese nivel de estabilidad. Entonces, por fin, tendré la vida espiritual que deseo.</p>",
    "<p>Entonces podré vivir en la granja. Entonces oraré más. Estaré más presente. Me conectaré con mayor profundidad con Dios, conmigo misma, con mi esposa y con mis amistades.</p>",
    "<p>Es como si me hubiera convencido de que la vida espiritual podrá comenzar una vez que tenga resuelta mi situación material.</p>",
    "<h2>Volver a encontrar el centro</h2>",
    "<p>Y últimamente me pregunto: ¿y si lo estoy viendo al revés? ¿Y si me estoy equivocando?</p>",
    "<p>¿Y si lo que este momento me pide no es regresar al extremo del que vengo, sino encontrar un punto de equilibrio?</p>",
    "<p>Volver a lo esencial: la oración, la meditación, las Escrituras, la presencia y el propósito. Soltar lo pasajero y dirigir mi atención hacia lo eterno.</p>",
    "<p>«Busquen primero el reino de Dios y su justicia, y todas estas cosas les serán añadidas».</p>",
    "<p>No quiero idealizar el pasado ni volver a abandonarme. Pero sí siento que necesito volver a poner lo espiritual en el centro y preguntarme cómo sería dejar que mis decisiones cotidianas nazcan de mis convicciones más profundas.</p>",
    "<p>¿Cómo se vive eso en la práctica, día tras día, cuando trabajo en una empresa y tengo un negocio en crecimiento? Todavía no tengo esas respuestas. Pero sé por dónde empezar.</p>",
    "<p>Voy a volver a orar. Con intención.</p>",
    "<p>Porque quizá el camino hacia la seguridad material que tanto he perseguido pase por la vida espiritual que llevo tiempo posponiendo. Tal vez sea verdad que, cuando busco primero el reino, lo demás encuentra su lugar.</p>",
    "<p>Y, si no es así, tal vez deje de importarme tanto.</p>",
    "<p>Quizá la plenitud espiritual transforme lo que creemos necesitar del mundo.</p>",
    "<p>No lo sé. Quería compartirte esta reflexión porque estoy segura de que no soy la única que intenta reconciliar estas dos partes de la vida.</p>",
    "<p>Con amor,</p>",
    "<p>ADL</p>",
  ].join(""),
} as const satisfies Record<string, string>;
