import { ClerkProvider } from "@clerk/nextjs";

import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Header } from "@/components/nav-bar";
import { Footer } from "@/components/footer";

import { Lora, Cormorant_Garamond } from "next/font/google";

import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app development team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${cormorantGaramond.variable} ${lora.variable} antialiased`}
        >
          <Toaster position="top-right" richColors />
          <SidebarProvider defaultOpen={false}>
            <AppSidebar className="font-[family-name:var(--font-cormorant-garamond)]" />
            <SidebarInset>
              <Header />
              {children}
              <Footer />
            </SidebarInset>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
